#!/bin/bash

# [Gedit Tool]
# Name=mocha
# Name[zh_CN]=mocha
# Comment=run mocha here
# Comment[zh_CN]=run mocha here
# Input=nothing
# Output=output-panel
# Applicability=all
# Save-files=nothing
# Languages=

#name=`echo $GEDIT_CURRENT_DOCUMENT_NAME | cut -d. -f1`
#dir=$GEDIT_CURRENT_DOCUMENT_DIR

path=$GEDIT_CURRENT_DOCUMENT_PATH
echo 'mocha '$path
mocha $path
